MOVIES.JS 
export const movies = [ { 
title: "Partiu América",
genre: "comédia", 
ageRating: Livre, 
synopsis: "Em Partiu América, Matheus (Matheus Ceará) é um dono de um parque de diversões muito simples do interior do Nordeste, que tem o sonho de conhecer os famosos parques dos EUA. De tão admirador desse mundo mágico, ele deu os nomes de Flórida (Luara Fonseca) e Stevenspilbi (Gabriel Palhares) para seus filhos que claro, também são fanáticos por esse universo. Mas, quando essa família finalmente tem a oportunidade de viajar para o exterior pela primeira vez, as coisas não saem como o esperado.

", 
trailer: "https://www.youtube.com/watch?v=1HS957R61Sk" 
}, 
{ 
title: "Joy o nome do Sucesso", 
genre: "comédia", 
ageRating: 10, 
synopsis: "Criativa desde a infância, Joy Mangano (Jennifer Lawrence) entrou na vida adulta conciliando a jornada de mãe solteira com a de inventora e tanto fez que tornou-se uma das empreendedoras de maior sucesso dos Estados Unidos", 
trailer: "https://www.youtube.com/watch?v=jbiMQqKGTxY" 
}, 
{ 
title: "Vizinhos", 
genre: "comédia", 
ageRating: 12, 
synopsis: "Mac (Seth Rogen) e Kelly Radner (Rose Byrne) acabaram de se mudar para uma casa nova, junto com o filho recém-nascido deles. Aparentemente trata-se do local perfeito para criar uma família, mas logo o casal percebe que as aparências enganam. Especialmente quando um dos vizinhos é Teddy Sanders (Zac Efron), que lidera os jovens das redondezas nas confusões aprontadas por eles.

", 
trailer: "https://www.youtube.com/watch?v=IaV-OO-Mwx0" 
}, 
{ 
title: "Intocáveis", 
genre: "comédia", 
ageRating: 14, 
synopsis: "Em, Intocáveis, Philippe (François Cluzet) é um aristocrata rico que, após sofrer um grave acidente, fica tetraplégico. Precisando de um assistente, ele decide contratar Driss (Omar Sy), um jovem problemático que não tem a menor experiência em cuidar de pessoas no seu estado. Aos poucos, Driss aprende a função, apesar das diversas gafes que comete. Philippe, por sua vez, se afeiçoa cada vez mais ao jovem por ele não tratá-lo como um pobre coitado. De pouco em pouco a amizade entre ambos vai se estabelecendo, conhecendo melhor um o mundo do outro.

", 
trailer: "https://www.youtube.com/watch?v=-Fb8h4gChlU" 
}, 
{ 
title: "Tá rindo de que?", 
genre: "comédia", 
ageRating: 16, 
synopsis: "George Simmons (Adam Sandler) é um popular comediante, que descobre que possui uma doença sanguínea incurável. Devido a ela, George tem apenas mais um ano de vida. Ira Wright (Seth Rogen) é um comediante em ascensão, que tem dificuldades em dissociar seus personagens dele próprio. George e Ira têm uma característica em comum: não possuem amigos próximos. Uma noite eles se conhecem quando farão apresentações no mesmo local. George contrata Ira para ser seu assistente pessoal, abrindo seus shows. Logo eles se tornam amigos, com George ensinando a Ira como conduzir o público do palco e Ira ajudando-o a encontrar seu legado.

", 
trailer: "https://www.youtube.com/watch?v=JuLrcUZpMKc" 
}, 
{ 
title: "Orgulho e preconceito", 
genre: "Romance", 
ageRating: Livre, 
synopsis: "Inglaterra, 1797. As cinco irmãs Bennet - Elizabeth (Keira Knightley), Jane (Rosamund Pike), Lydia (Jena Malone), Mary (Talulah Riley) e Kitty (Carey Mulligan) - foram criadas por uma mãe (Brenda Blethyn) que tinha fixação em lhes encontrar maridos que garantissem seu futuro. Porém Elizabeth deseja ter uma vida mais ampla do que apenas se dedicar ao marido, sendo apoiada pelo pai (Donald Sutherland). Quando o sr. Bingley (Simon Woods), um solteiro rico, passa a morar em uma mansão vizinha, as irmãs logo ficam agitadas. Jane logo parece que conquistará o coração do novo vizinho, enquanto que Elizabeth conhece o bonito e esnobe sr. Darcy (Matthew Macfadyen). Os encontros entre Elizabeth e Darcy passam a ser cada vez mais constantes, apesar deles sempre discutirem.

", 
trailer: "https://www.youtube.com/watch?v=Y6XneqkfD3c" 
}, 
{ 
title: "Um romance",
genre: "Romance", 
ageRating: 10, synopsis: "Pedro (Wagner Moura) é um ator e diretor de teatro, que se apaixona por Ana (Letícia Sabatella), também atriz, ao contracenar com ela a peça "Tristão e Isolda". O namoro deles é afetado pelo posterior sucesso dela na TV, impulsionado pela empresária Fernanda (Andréa Beltrão). Além disto, ao gravar um especial de TV, Ana conhece Orlando (Vladimir Brichta), um ator por quem se apaixona.

", 
trailer: "https://www.youtube.com/watch?v=R8tVhUFJ1Js" 
}, 
{ 
title: "Lembranças", 
genre: "Romance", 
ageRating: 12, synopsis: "Nova York. Tyler Roth (Robert Pattinson) é um jovem rebelde que não tem uma boa relação com o pai, Charles (Pierce Brosnan), desde que uma tragédia abalou sua família. Ele divide um apartamento com Aidan (Tate Wellington) e com ele sai para uma boate. Ao deixar o local, Tyler se intromete em uma briga. Neil Craig (Chris Cooper), um policial traumatizado pelo assassinato de sua esposa dez anos antes, é chamado ao local. Ele libera Tyler e Aidan mas, após uma provocação de Tyler, lhe dá uma surra e manda prendê-lo. Dias depois, Aidan descobre que Ally (Emilie de Ravin), a filha de Neil, estuda com eles. Ele propõe a Tyler que tente conquistá-la, para se vingar. Inicialmente relutante, Tyler aceita a proposta. Só que, aos poucos, se apaixona por Ally.

", 
trailer: "https://www.youtube.com/watch?v=Gq8L6xRm5I8" 
}, 
{ 
title: "Continência ao amor", 
genre: "Romance", 
ageRating: 14, synopsis: "Em Continência ao Amor, Cassie Salazar (Sofia Carson) é uma cantora em ascensão que quer sair da bolha. Para pagar o aluguel e suas doses de insulina, ela trabalha em um bar todas as noites com sua banda. Porém, suas doses diárias de remédio são muito caras e ela não consegue pagar um convênio médico e acaba atrasando outras contas para que consiga sobreviver. Isso até que ela vê em um contrato que, ao casar com um membro do exército dos EUA, o cônjuge ganha também um convênio médico e o salário aumenta. É com isso que ela conhece Luke Morrow (Nicholas Galitzine), um fuzileiro naval, que é parceiro de seu amigo de escola. Porém, ambos são de personalidades totalmente opostas, mas precisam forjar um casamento por conta de suas necessidades pessoais. Será que os dois conseguirão fingir um casamento amoroso por tanto tempo? Ou será que os dois vão acabar se apaixonando de verdade no processo?

", 
trailer: "https://www.youtube.com/watch?v=2yyzb9RDUgs" 
}, 
{ 
title: "Amor de redenção", 
genre: "Romance", 
ageRating: 16, synopsis: "Baseado no best-seller de Francine Rivers, Amor de Redenção é uma adaptação da história bíblica de Oseias e Gomer. Em plena Corrida do Ouro em 1850, Angel não espera nada dos homens além de traição. Vendida para a prostituição quando criança, ela sobrevive mantendo seu ódio vivo. E o que ela mais odeia são os homens que a usam, deixando-a vazia e morta por dentro. Então ela conhece Michael Oséias. Um homem que busca o coração de seu Pai em tudo, ele obedece ao chamado de Deus para se casar com Angel e amá-la incondicionalmente. Lentamente, dia após dia, ele desafia todas as expectativas amargas de Angel até que, apesar de sua resistência, seu coração congelado começa a derreter. Mas com seu abrandamento inesperado vêm sentimentos esmagadores de indignidade e medo. De volta à escuridão, longe do amor perseguidor de seu marido, aterrorizada com a verdade que ela não pode mais negar: sua cura final deve vir daquele que a ama ainda mais do que Michael Oséias.

", 
trailer: "https://www.youtube.com/watch?v=-cHf6aRumBM" 
}, 
{ 
title: "Shrek", 
genre: "animação", 
ageRating: Livre, synopsis: "Em um pântano distante vive Shrek (Mike Myers), um ogro solitário que vê, sem mais nem menos, sua vida ser invadida por uma série de personagens de contos de fada, como três ratos cegos, um grande e malvado lobo e ainda três porcos que não têm um lugar onde morar. Todos eles foram expulsos de seus lares pelo maligno Lorde Farquaad (John Lithgow). Determinado a recuperar a tranquilidade de antes, Shrek resolve encontrar Farquaad e com ele faz um acordo: todos os personagens poderão retornar aos seus lares se ele e seu amigo Burro (Eddie Murphy) resgatarem uma bela princesa (Cameron Diaz), que é prisioneira de um dragão. Porém, quando Shrek e o Burro enfim conseguem resgatar a princesa logo eles descobrem que seus problemas estão apenas começando.

", 
trailer: "https://www.youtube.com/watch?v=CwXOrWvPBPk" 
}, 
{ 
title: "Coraline", 
genre: "animação", 
ageRating: 10, synopsis: "Entediada em sua nova casa, Caroline Jones (Dakota Fanning) um dia encontra uma porta secreta. Através dela tem acesso a uma outra versão de sua própria vida, a qual aparentemente é bem parecida com a que leva. A diferença é que neste outro lado tudo parece ser melhor, inclusive as pessoas com quem convive. Caroline se empolga com a descoberta, mas logo descobre que há algo de errado quando seus pais alternativos tentam aprisioná-la neste novo mundo.

", 
trailer: "https://www.youtube.com/watch?v=m9bOpeuvNwY" 
}, 
{ 
title: "One Piece Red", 
genre: "animação", 
ageRating: 12, synopsis: "Uta - a cantora mais amada do mundo. Sua voz, com a qual ela canta enquanto esconde sua verdadeira identidade, foi descrita como "de outro mundo". Ela aparecerá em público pela primeira vez em um show ao vivo. Enquanto o local se enche de todos os tipos de fãs de Uta - piratas animados, a Marinha assistindo de perto e os Chapéus de Palha liderados por Luffy que simplesmente vieram para curtir sua performance sonora - a voz que o mundo inteiro estava esperando está prestes a ressoar. A história começa com o fato chocante de que ela é "filha de Shanks".

", 
trailer: "https://www.youtube.com/watch?v=JvqcaQJgr-A" 
},
{ 
title: "Naruto the movie", 
genre: "animação", 
ageRating: 14, 
synopsis: "A Lua está em rota de colisão com a Terra, e pode se chocar com o planeta na forma de um meteoro. Enquanto isso, Hanabi é sequestrada por um estranho homem. Cabe a Naruto, Shikamaru, Hinata, Sakura e Sai salvar Hanabi e consertar a situação.

", 
trailer: "https://www.youtube.com/watch?v=fTVpFn0Mb3Q" 
}, 
{ 
title: "Perdi meu corpo", 
genre: "animação", 
ageRating: 16, 
synopsis: "Uma mão decepada escapa do laboratório de dissecação no qual estava presa durante os últimos meses. Com a fuga ela possui um só objetivo: retornar para o restante de seu corpo e voltar a fazer parte de um organismo completo. Enquanto ela vaga pelos arredores de Paris, se lembra dos tempos de quando era apenas uma jovem mão no corpo de um apaixonado rapaz.

", 
trailer: "https://www.youtube.com/watch?v=eu-A1LRPdpA" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 18, 
synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, 
synopsis: "", 
trailer: "" 
} 
];
